### ISSUE TITLE
Registering for an event

### ISSUE THREAD

**Issue by WSU-Car** [MistyCommunity/Python-SDK#2]
Hello, Thanks for providing the Python SDK. I tried to use it. I am able to do basic things such as change LED, moveArms, etc… However, I am having problem with successful registering to events. As an example, I tried to register to the IMU Event Type as shown below. But I am not getting any data back even after waiting for a long time. Please see a sample below.

************* RUN-able code after entering the right IP address ************
```
from mistyPy.Robot import Robot
from mistyPy.Events import Events
from mistyPy.EventFilters import EventFilters

if name == “main”:
try:
# First create the robot object
ip_address = “xx.xx.xx.xx”
misty = Robot(ip_address)

    _Data = misty.RegisterEvent(event_name="IMU_data", event_type=Events.IMU)
    print(misty.active_event_registrations)
    print(_Data.data)
    print(_Data.event_name)
    print(_Data.event_type)
    print(_Data.is_active)
    print(_Data.data["message"])

    misty.KeepAlive()

except Exception as ex:
    print(ex)
finally:
    # Unregister events if they aren't all unregistered due to an error
    misty.UnregisterAllEvents()
```

The result from the print() statements is as below.
{‘IMU_data’: <mistyPy.Events.Event object at 0x00000256BE942B20>}
{‘status’: ‘Not_Subscribed or just waiting for data’}
None
IMU
True
‘message’

If I am understanding it correctly, the registration to the IMU event type is active (per the first print() statement result). Then in the next statement, it says ‘Not subscribed or waiting for data’. I have tried waiting for a very long time (~10minutes or so) and I don’t see any data coming back. For _Data.event_name, I was expecting “IMU_data” but it is giving me None… Lastly, I don’t see the desired results in _Data.data["message].

I would really appreciate any help here. Thanks!

**Comment by rfarkas** [comment]
I've got the same issue. I can do basic operations with my Misty, but I cannot receive any event data.
I tried both approach on registering BumpSensor event but behaves exactly the same as WSU-Car described above.
Thank you in advance for any fix!

**Comment by WSU-Car** [comment]
It appears that I was missing this statement in the code:    **while "just waiting for data" in str(_Data.data):** 
After I added it, I got expected results.

```
from mistyPy.Robot import Robot
from mistyPy.Events import Events
from mistyPy.EventFilters import EventFilters

if __name__ =="__main__":
    try:
        # First create the robot object
        ip_address = "IP ADDRESS"
        misty = Robot(ip_address)

        _Data = misty.RegisterEvent("IMU_data", Events.IMU)


        # Wait for the event to get some data before printing the message
        while "just waiting for data" in str(_Data.data):
            pass
        print(misty.active_event_registrations)
        print(_Data.data)
        print(_Data.event_name)
        print(_Data.event_type)
        print(_Data.is_active)
        print(_Data.data["message"])

        #misty.KeepAlive()

    except Exception as ex:
        print(ex)
    finally:
    # Unregister events if they aren't all unregistered due to an error
        misty.UnregisterAllEvents()
```


Result I got was the following:
{'IMU_data': <mistyPy.Events.Event object at 0x7fc1ca1ecd00>}
{'eventName': '5915574318', 'message': {'created': '2021-07-09T18:33:58.9953372Z', 'pitch': 358.6715797518953, 'pitchVelocity': 0.0, 'roll': 359.53101644459156, 'rollVelocity': 0.0, 'sensorId': 'imu', 'xAcceleration': -0.08, 'yAcceleration': 0.21, 'yaw': 92.0743176775233, 'yawVelocity': 0.0, 'zAcceleration': -9.8}}
5915574318
IMU
True
{'created': '2021-07-09T18:33:58.9953372Z', 'pitch': 358.6715797518953, 'pitchVelocity': 0.0, 'roll': 359.53101644459156, 'rollVelocity': 0.0, 'sensorId': 'imu', 'xAcceleration': -0.08, 'yAcceleration': 0.21, 'yaw': 92.0743176775233, 'yawVelocity': 0.0, 'zAcceleration': -9.8}

**Comment by WSU-Car** [comment]
Issue resolved. See example above

**Comment by rfarkas** [comment]
Dear WSU-Car,

Your code stacks in the while loop for me :(
The playaudio in the slightly extended code below is executed and the event is registered, but it always receives {'status': 'Not_Subscribed or just waiting for data'}.

I'm using python 3.9.1, Win10, Visual Studio Code.
Any suggestion maybe?
 
cheers

```
from mistyPy.Robot import Robot
from mistyPy.Events import Events
from mistyPy.EventFilters import EventFilters
from mistyPy.GenerateRobot import RobotGenerator

import sys, os
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

if __name__ == "__main__":
    try:
        # First create the robot object
        ip_address = "192.168.0.100"
        RobotGenerator(ip_address)
        misty = Robot(ip_address)
        misty.UnregisterAllEvents()
        
        _Data = misty.RegisterEvent("IMU_data", Events.IMU)

        misty.PlayAudio("s_Awe.wav")

        print(misty.active_event_registrations)
        print(_Data.data)
        
        # Wait for the event to get some data before printing the message
        while "just waiting for data" in str(_Data.data):
            pass
        
        print(_Data.data)
        print(_Data.event_name)
        print(_Data.event_type)
        print(_Data.is_active)
        print(_Data.data["message"])

    except Exception as ex:
        print(ex)
    finally:
        # Unregister events if they aren't all unregistered due to an error
        misty.UnregisterAllEvents()



```

**Comment by WSU-Car** [comment]
@rfarkas , I tested it on Ubuntu 20.04, Python 3.8.10 and Visual Studio Code. I do not think Windows 10 is a problem but you may want to test it on Ubuntu if you have access to it. 

Also, are you able to see the IMU data in the Command Center - just to make sure it is transmitting the data? I would try to test with other events such as below. 
misty.RegisterEvent("right_arm", Events.ActuatorPosition, condition=[EventFilters.ActuatorPosition.ArmRight])

Could you try to run the exact same code that I have above without any modifications to it (except for the IP address ofcourse). I suspect that because you have the following statement before the while (........), that may be the problem.
print(_Data.data)

I hope this helps.Thanks.
